### ISSUE TITLE
Can't seem to get this to work when deploying.

### ISSUE THREAD

**Issue by huntson** [xemle/home-gallery#101]
I've got the following for my docker-compose in stacks in Portainer

version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
      #- GALLERY_API_SERVER_CONCURRENT=1 # On low powered devices
      #- GALLERY_API_SERVER_TIMEOUT=60 # On low powered devices
      - GALLERY_OPEN_BROWSER=false
      # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
      - GALLERY_WATCH_POLL_INTERVAL=300
    volumes:
      - /share/CACHEDEV1_DATA/docker/homegallery/data:/data
      # Mount your media directories below /data
      - /share/CACHEDEV1_DATA/docker/homegallery/data/Pictures:/data/Pictures
    ports:
      - "3010:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']

No matter what I keep getting this in the docker logs:

  [2023-11-14 02:02:33.163]: cli.run error Error: Error: Configuration file /data/config/gallery.config.yml does not exist

I have attempted to manually create a gallery.config.yml and that still doesn't work.

**Comment by xemle** [comment]
Hi. Did you try to initialize the config as describe in the [installation docs](https://docs.home-gallery.org/install/index.html#id8)? Alternativly you can copy and modify your config from [gallery.config-example.ym](https://github.com/xemle/home-gallery/blob/master/gallery.config-example.yml) and edit the sources something to

```
sources:
  - ~/Pictures
```

Your base directory is `/share/CACHEDEV1_DATA/docker/homegallery/data`. The config needs to be added than in `/share/CACHEDEV1_DATA/docker/homegallery/data/config`

**Comment by huntson** [comment]
The subfolder of 'config' is what I was missing.  Putting the .yml file I had already generated inside of that (after creating it) solved the startup issue.  Now to other issues

**Comment by rykou** [comment]
have the same issue, just using docker compose, seems to be broken,

**Comment by xemle** [comment]
@rykou how is your mounted folder structure of `/data`? There should be a `/data/conig/gallery.config.yml` after initialization.

If possible, please provide the log output for better analysis of your error.

**Comment by rykou** [comment]
@xemle 
Logs from the Gallexy-1 Docker

[2024-03-03 17:29:48.937]: cli.run error Error: Error: Configuration file /data/config/gallery.config.yml does not exist

its all it has,

this is the compose i use on portainer running on Raspberry pi 4

`version: "3.9"
services:
  api:
    # custom build via
    #build: packages/api-server
    image: xemle/home-gallery-api-server
    environment:
      # TensorflowJS backends
      # - cpu: slowest and best support
      # - wasm: good perfromance for arm64 and amd64 platforms
      # - node: best performance on amd64 platform
      #- BACKEND=cpu
      - BACKEND=wasm
      #- BACKEND=node
  gallery:
    # custom build via
    #build: .
    image: xemle/home-gallery
    environment:
      - GALLERY_API_SERVER=http://api:3000
      - GALLERY_API_SERVER_CONCURRENT=1 # for SoC devices like Rasperry Pi. Use 5 otherwise
      - GALLERY_API_SERVER_TIMEOUT=60 # for SoC devices like Rasperry Pi. Use 30 otherwise
      #- GALLERY_USE_NATIVE=ffprobe,ffmpeg,vipsthumbnail # On issues with sharp resizer
      - GALLERY_OPEN_BROWSER=false
      # Use polling for safety of possible network mounts. Try 0 to use inotify via fs.watch
      - GALLERY_WATCH_POLL_INTERVAL=300
    volumes:
      - ./data:/data
      # Mount your media directories below /data
      - /mnt/photos:/data/Pictures
    ports:
      - "3000:3000"
    user: "${CURRENT_USER}"
    entrypoint: ['node', '/app/gallery.js']
    command: ['run', 'server']`
    
    
![Screenshot 2024-03-03 173255](https://github.com/xemle/home-gallery/assets/15199165/62460b2f-c40e-4bbc-bfcd-304f5a3d6430)


API server logs attached 
[_picturemanagement-api-1_logs.txt](https://github.com/xemle/home-gallery/files/14473930/_picturemanagement-api-1_logs.txt)

Enviroment : 
![Screenshot 2024-03-03 173458](https://github.com/xemle/home-gallery/assets/15199165/da1542ab-1035-4a0a-bb9d-38c151df2abf)

**Comment by rykou** [comment]
For me it seems the image from docker, is not creating the default gallery.config

**Comment by xemle** [comment]
Have you followed the installation instructions for docker compose?

```
mkdir -p data
echo "CURRENT_USER=$(id -u):$(id -g)" >> .env
docker compose run gallery run init --source /data/Pictures
docker compose up -d
```

**Comment by rykou** [comment]
> Have you followed the installation instructions for docker compose?
> 
> ```
> mkdir -p data
> echo "CURRENT_USER=$(id -u):$(id -g)" >> .env
> docker compose run gallery run init --source /data/Pictures
> docker compose up -d
> ```

Hi, 

These instructions are very vague,  where should i run this? inside the docker after i have used the compose, or outside (but there is already a data folder on the linux root, 

After that,
docker compose run gallery run init --source /data/Pictures 
This is supposed to run at the docker is "gallery"  something that is supposed to exist by just using the Compose or should we be using the Container ID instead, 

also --source /data/Picture does not exist in the root system (nor inside the container)

please can you be more clear on these documentation? or maybe setup in a way that the compose is enough

**Comment by xemle** [comment]
Hi @inuonly

thank you for your detailed response and your concerns. HomeGallery is an open source project and relies on feedback, discussions and contributions.

It is also a spare time project and exists for fun. Therefore the time is limited and it is quite hard to find the right end user level. My assumption is, that there are some basic understanding how some stuff is working like docker and docker compose. So the basic usage of docker and docker compose is out of scope of the documentation. (But of cause, it can be added if someone is contribute it via a PR).

The documentation should provide enough hints how to run it with docker compose. Other environments like portainer or proxmox. While the usage should be quite similar, it is not covered in the documentation. It is not covered be cause I am not using it and no one contributed a installation guide so far.

I try to answer as best as I can and try to understand the issue here. If you bring some time and patient we can try to find a solution to get the gallery running on your side. But at the moment I do not know where to start with the help.

Are there issues running portainer in general? Do you have an understanding how to run compose files in portainer? Do you know how to mount volumes? Maybe we should clarify your issue in a real-time session via [discord](https://discord.gg/kbvmvadCwe)?

The basic idea is that the HomeGallery container ships the software and needs to read your images and will serve you a gallery. The access and reading of your files is done via volumes. The [documentation](https://docs.home-gallery.org/install/index.html#docker-compose) tells that in following lines about the `compose.yml` files

```yml
    volumes:
      - ./data:/data
      # Mount your media directories below /data
      - ${HOME}/Pictures:/data/Pictures
```

So your local path `${HOME}/Pictures` is mapped to the container path `/data/Pictures`. `${HOME}/Pictures` needs to be adjusted to your needs and your local disk layout.

Then the gallery needs to be configured and needs to know where your images are located. Which is done via

```bash
docker compose run gallery run init --source /data/Pictures
```
So this instruction calls the CLI (which is `docker compose run gallery` for docker compose setups) with the arguments `run init --source /data/Pictures` where `/data/Pictures` is the mapped volume inside the container which is at the end your local `${HOME}/Pictures` directory. This is also only an example and you might have several volumes and you can adjust it to your local setting or your container volume paths.

If any questions are still open, please do not hesitate to ask your questions in [discord](https://discord.gg/kbvmvadCwe) and we can agree on some date and times to solve your issues. Then it is also easier to find the right level of abstraction and to spot your issue.

**Comment by xemle** [comment]
@inuonly 

Thank you for your reply.

> i have seen a way to add that to docker compose file itself. And that as what I was tryin to say if that is added might solve the config not found issue showing in portainer logs of docker container

Do I understand you correctly that it would be a help for you if the quickstart section is:

```bash
mkdir -p gallery/data
cd gallery
# copy and adjust compose.yml from above
echo "CURRENT_USER=$(id -u):$(id -g)" >> .env
docker compose run gallery run init --source /data/Pictures
docker compose up -d
```

Please continue to ask questions for clarifications. It is just complex to cover every usecase. And with your help we can fix one of them.

**Comment by xemle** [comment]
@inuonly Can we close this issue?

**Comment by xemle** [comment]
@inuonly you are right. My fault
