### ISSUE TITLE
Display additional metadata

### ISSUE THREAD

**Issue by huntson** [xemle/home-gallery#102]
Unless I'm missing something I don't see a way in the Web UI nor the config file to display things like th file name in addition to showing the previous in the photo spread view.

**Comment by xemle** [comment]
Please use the info icon (i) in the single view to see the image details like in the [demo gallery](https://demo.home-gallery.org/view/4ec1e5e00ca9)

**Comment by huntson** [comment]
So there's no way to do this when viewing multiple pictures?

**Comment by xemle** [comment]
Currently not. PRs are welcome.

What is your usecase to see the filenames in the photo stream? What do you like to see, to use or to solve so that I can understand your requirement better?

**Comment by huntson** [comment]
I'm using this with several family videos and the first frame of a lot of the videos starts in black.  it would be helpful for folks to know what they are clicking on before clicking it.

**Comment by xemle** [comment]
OK. Understand. And why there are many videos starting in black? Are these postprocessed with an intro?

Are your filenames meaningful, so that it helps to identify these videos?

Are there any chances to have a title image of the video? Eg "Summer 2023.mp4" as main file and "Summer 2023.jpg" as title image? So the Gallery can show this one instead of the first frame (as a new feature)?

**Comment by huntson** [comment]
It's how the videos are.  Usually within the first few seconds something like the title card you suggest does appear.  This being said, I don't want to have to trim these videos so they all start later as that kind of defeats the purpose of putting this together and making it easy.

**Comment by xemle** [comment]
Thank you for the clarification. I can understand your need better.

IMHO the UI should focus on the image. For me filenames are usually cryptic due timestamps. Usually it is to difficult to rename each file to a meaningful filename so in general this information does not give any value and distracts.

I could imagine to have different view modes where one mode shows the filenames and other stuff like tags or detected objects.

But on your case I could imagine that it would be better to customize the preview image. One simple solution is to provide a custom time offset for all video thumbnails/poster.

The other option (which I do prefer) is to provide a custom sidecar file as video thumbnail since your usecase with black intro starts is special. Then you can choose a custom frame which can be extracted manually in batch. This solution is flexible and a complex thumbnail suenatio is resolved by the user which is difficult to be solved by a algorithm.

This feature would bring a general value and keeps the UI informative and simple. However it needs to be implemented but the changes should not be too complex...

What do you think?

**Comment by Dukobpa3** [comment]
Generate 5slides gifs? 5% timeline, 25, 50, 75, 95?

(5 and 95 instead of 0/100 to avoid start/end titles, black screens etc)

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
