### ISSUE TITLE
Sharing a collection of images with third parties with a URL link

### ISSUE THREAD

**Issue by madmak** [xemle/home-gallery#109]
Hello to all contributors.
I looked at the project and I really liked it. I want to use it, but I'm missing something that I couldn't find. Is it possible to share a collection of images?

**Comment by xemle** [comment]
Hi @madmak 

I'm happy, that you like HomeGallery.

Regarding sharing there are currently 2 possibilities

 - Create a user so the whole gallery can be viewed password protected or
 - Export a subset by a query as static web gallery. You can use random prefix for it so the public can not guess the URL and users access the files without a password

Users are currently not limited to a subset of the gallery since it was a design decision to reduce the complexity of this spare time project.

Further download of original files was previous requested but not yet implemented since I do not have a personal requirement for it.

For both PRs are welcome and I can assist for implementation questions.

**Comment by madmak** [comment]
Hi @xemle 
Thank you very much for your quick response and attention.
Now let's check if I understood your suggestion correctly. 
Do you suggest I run a second instance of the gallery but with a unique URL so that it can only be seen by its owners?

**Comment by madmak** [comment]
Oh! I understand.
You suggest using a command line tool to generate a static website with images.
Again, many thanks for the quick reply.

**Comment by xemle** [comment]
Correct. My usecase is to offer family members of a larger event a static export gallery. I set a random prefix so that user can access them easily without any hassle e.g. by https://example.com/coeWd8eDh4BS where `coeWd8eDh4BS` is the `--base-path` argument value of the [export command](https://docs.home-gallery.org/cli/index.html#export-static-command).

Or you implement this feature that users can be limited to a subset of the gallery by a query expression ;-)

**Comment by xemle** [comment]
Have you also checked other open source self hosted galleries? Maybe they are also worth for an evaluation. Dont get me wrong, I am happy when you stay but I am also not sorry if some other software fits your need better.

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
