### ISSUE TITLE
Request to add a switch to turn off the image position.

### ISSUE THREAD

**Issue by lhuanyun** [xemle/home-gallery#110]
I think exposing one's location on the Internet is a very dangerous thing, and a global switch is needed to turn off the picture location function.

**Comment by xemle** [comment]
Hi @lhuanyun

thank you for evaluating HomeGallery and for raising your concerns. There is a similar issue #53 with some recent comments. You can disable the geo reverse service by entering an invalid URL. For other solutions PRs are welcome.

> I think exposing one's location on the Internet is a very dangerous thing

Can you provide some more details why you think that the geo reverse is a dangerous thing because I am a bit lost and I do not share this option. I would like to understand your motivation in detail. IMHO the geo reverse lookup is a great feature. But this is absolute my personal opinion.

The geo lookup is only triggered if your media has geo information. So I guess if your prefer a high grade of privacy your images wont have such information anyway and the service is not used.

**Comment by lhuanyun** [comment]
First of all, I am very grateful to the author for taking the time to respond to my questions. I also really like the picture location feature, but I wanted to use this project for some of my own day-to-day photography. There might be some in my garage, some in my house, some in my workplace, some of my hangouts. I don’t want some people around me or strangers on the Internet to peek into my life and the places where I often appear, because this includes the safety of my family.

**Comment by lhuanyun** [comment]
Even if I set it up like this, newly added photos will still show specific positioning. I've cleared all caches and databases.![image](https://github.com/xemle/home-gallery/assets/20707383/5958891b-e3f4-4050-af4b-5d035a31088d)

**Comment by lhuanyun** [comment]
![image](https://github.com/xemle/home-gallery/assets/20707383/ae299859-bbed-44f8-a210-34e89681edea)

**Comment by xemle** [comment]
Hi @lhuanyun 

thank you for your response. It becomes clearer to me, why you want to disable the geo feature.

To remove the geo information: As mentioned in #53 if there are already geo reverse information processed and stored via the extractor step, the database creation uses this information. To loose all geo reverse information you have to delete all `*-geo-reverse.json` files in the storage directory and rerun the import to update the extracted information and to rebuild the database.

Further I would kindly ask you how you like to use HomeGallery. Would you like to have only a public gallery or private and public version? For private version (also with password protected access) I currently do not see a benefit to disable sensitive data since it is used private and shared with a few people. For the public version I am aware that some information reveal some private data such as geo data or even the folder structure.

I am using the gallery private with all data and I am creating a static export for the public [demo gallery](https://demo.home-gallery.org). The images for the public are well selected which should not have private content like family members or to much pictures from my home location. Further it is a static version for safety reasons since I do not want to take the risk that someone compromise the server component via nodejs security issues and access my original files - even I wrote the server with my best knowledge... And it still contains the original folder structure which bugs me.

So I recommend to use the static export for full public galleries.

And I could imagine that the static export supports some anonymization flags to anonymize folder names, remove face detection, or the geo information. So the user can decide which information will be anonymized on the static export. That would help you and me. What do you think?

**Comment by SleepyStudent** [comment]
Hi and thanks for a super nice gallery! I have an related request. I would like to disable the reverse geo location functionality but keep the coordinates in the gallery image information. Would it be possible to add the options to skip the reversing when indexing images? 
Something like the `disable` options for `apiServer` in the yaml-config.

```
...
  apiServer:
    url: https://localhost
    timeout: 30
    concurrent: 5,
    disable:
      - similarDetection
      - objectDetection
      - faceDetection
  geoReverse:
    url: https://localhost
...
```
to
```
...
  geoReverse:
    url: https://localhost
    disable:
    - geoReverse
...
```

**Comment by lhuanyun** [comment]
Thank you very much for the author's attention, I am very busy, and the reply is late. 

I took a look at the static web page function. In fact, I prefer to run the service directly. Regarding the problem of the mentioned nodejs that may lead to the leakage of the system directory, it is really a bit scary. Thank you very much for the authors for some improvements and dedication. Very good

**Comment by lhuanyun** [comment]
![image](https://github.com/xemle/home-gallery/assets/20707383/f9b2d2d4-96b8-4cfd-92ce-6fce2a065838)

oh ， so cute 。thanks ^v^

**Comment by xemle** [comment]
> Hi and thanks for a super nice gallery!

Thank you

> I have an related request. I would like to disable the reverse geo location functionality but keep the coordinates in the gallery image information. Would it be possible to add the options to skip the reversing when indexing images? Something like the `disable` options for `apiServer` in the yaml-config.
>
> The reason for this is that it takes some time to index with the invalid geo-URL

I was not aware, that the extraction delays due the invalids calls.

Currently your requested feature not implemented. PRs are welcome supporting it. Maybe if the `geoReverse.url` is set to `false` the extractor could skip it.

```
  geoReverse:
    url: false
```
The [task method](https://github.com/xemle/home-gallery/blob/master/packages/extractor/src/extract/meta/geo-reverse.js#L48) could check for this value and can skip the method.

Why I am not implementing/fixing it by my own? This project is a spare time project and I am working on another part of the gallery right now. My time is limited to fix every requests and I am relying on your help. You have to wait until I find time for it or promote a PR. I can give guidance to get into the dev environment.

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
