### ISSUE TITLE
Provide light theme and add a theme switcher

### ISSUE THREAD

**Issue by CuB3y0nd** [xemle/home-gallery#120]
Hi, I really like this project, but I wish it could have a light theme.

**Comment by xemle** [comment]
Hi @CuB3y0nd 

I am happy that you like this project.

Since this is a spare time project time is limited and some features like a light theme depends on public contributions. Recently the styling was rewritten using Tailwind CSS. You can check how [theme switching](https://tailwindcss.com/docs/dark-mode) works there and provide your feature request as PR.

Do not hesitate to ask for further help

**Comment by CuB3y0nd** [comment]
Ok, i can try if have free time.

**Comment by CuB3y0nd** [comment]
> Hi @CuB3y0nd
> 
> I am happy that you like this project.
> 
> Since this is a spare time project time is limited and some features like a light theme depends on public contributions. Recently the styling was rewritten using Tailwind CSS. You can check how [theme switching](https://tailwindcss.com/docs/dark-mode) works there and provide your feature request as PR.
> 
> Do not hesitate to ask for further help

Ok, i can try if have free time.
