### ISSUE TITLE
Request to add a switch to turn off the image position

### ISSUE THREAD

**Issue by lhuanyun** [xemle/home-gallery#128]
I think exposing one's location on the Internet is a very dangerous thing, and a global switch is needed to turn off the picture location function.

**Comment by lhuanyun** [comment]
![image](https://github.com/xemle/home-gallery/assets/20707383/4c4d3b58-f357-4c17-b297-89ff39afa79d)

**Comment by xemle** [comment]
Hi @lhuanyun 

thank you for your input. I am a bit puzzled, since you opened #110 and we have there already a discussion about the position. With this issue #128 would you like to share your provided configuration with others?

Or do I miss any new request besides #110? How can I separate both requests?

**Comment by xemle** [comment]
Closing this issue due inactivity.

Please reopen it, if it becomes active again.
