### ISSUE TITLE
Add numbers in year view

### ISSUE THREAD

**Issue by ItsNoted** [xemle/home-gallery#28]
It would be great to see the ammount of media in the Years view like it shows in tags view.

![home-gallery-years](https://user-images.githubusercontent.com/57927413/165318309-345be1bd-ebb9-4c38-8118-d8cf837fa342.png)

**Comment by xemle** [comment]
Thank you for your input.

In [Years.tsx](https://github.com/xemle/home-gallery/blob/master/packages/webapp/src/year/Years.tsx#L21) the result should be than a Map of year -> amount to add this information to the view.

A PR is welcome to fix it. Otherwise I it comes to the list for the after-vacation-time in about a week.

**Comment by xemle** [comment]
BTW are you evaluating this web gallery for your YouTube channel ;-)

**Comment by xemle** [comment]
Awesome article. Thanks a lot for the evaluating, reviewing and citing my gallery

**Comment by xemle** [comment]
Hi @geekedtv I've implemented the amounts of media, image and videos in 6c3446b. See the [demo gallery](https://demo.home-gallery.org):

![image](https://user-images.githubusercontent.com/261850/167291015-71c29bd1-5cc2-4a5f-8718-85f9b4e13eb6.png)

**Comment by xemle** [comment]
Closing this ticket as solved
