### ISSUE TITLE
Search tags in the Tags page

### ISSUE THREAD

**Issue by asitemade4u** [xemle/home-gallery#32]
Fisrt, let me tell you how much I like HomeGallery: fast, lightweight -- the perfect complement to heavier solutions like digiKam or PhotoPrism.
I have tagged my photo assets with a lot of tags in digiKam and they are well recognized by HG.
But, due to their number, the Tags page becomes difficult to use.

What would help: a search box reducing the number of tags displayed when input.
A much better solution than the standard search box of the browser IMO as that one only selects the tags in the long list.

**Comment by xemle** [comment]
> Fisrt, let me tell you how much I like HomeGallery: fast, lightweight -- the perfect complement to heavier solutions like digiKam or PhotoPrism.

Thank you very much for the compliment. Especially that you cite PhotoPrism. For me PhotoPrism seems to be the best alternative for the web photo gallery HomeGallery (for me) and I am honored that you prefer HomeGallery.

For curiosity could you describe your usecase/need which you like to solve with HomeGallery? What is you preferred workflow/task you are looking for?

> I have tagged my photo assets with a lot of tags in digiKam and they are well recognized by HG.

Glad that the import of tags works well. This feature was an input of #11 from [smolin](https://github.com/smolin)

> But, due to their number, the Tags page becomes difficult to use.
> 
> What would help: a search box reducing the number of tags displayed when input. A much better solution than the standard search box of the browser IMO as that one only selects the tags in the long list.

For me your proposal is not that clear: You would like to list all available tags via the navbar "Tags" and like to search for a specific tag by filtering it on the top of the tag list because the list is too long to be helpful. Right?

And just to understand your motivation/workflow behind it in detail: What is your need behind it? E.g. why not using the similarity feature to capture all mountain images like on the [demo page](https://demo.home-gallery.org/similar/e1c2b95af002fed535366d4d49260f9e92fe7e75) without using manual edited tags?

Thank your for valuable input

**Comment by asitemade4u** [comment]
Hi Sebastian, and thank you for your quick response.
Here are mine:

## PhotoPrism
PhotoPrism is good, although not as good as digiKam IMO, notably when dealing with keywords (but better in other areas, notably geolocation). But since I wanted a self hosted solution I could share with collaborators on the network, I also used PhotoPrism.

## My use case with HomeGallery: 
since it is so fast and efficient, I mainly use it as a search engine for photos I previously tagged and geolocated with digiKam. So, the workflow is:
1. I tag and geolocate the pictures on digiKam
2. Syncthing transfers them on another server where several instances oh HomeGallery are installed, depending on the type of image (movie screenshots, photos as of now)
3. HomeGallery indezes them and they become readiily available for search

## Tags
- The Tags page is great but difficult to use when you have as many tags as I do (later on that below). Yes, it would be great to have a specific search box on the Tags page to filter the ones displayed. It should work either on whole words or part of words (eg. 'greek' finds "neo-Greek", "Greek art", "Greek Island", etc.)
- I understand you are very enthused by the similarity feature ;o)) But it is not helpful for me: I am dealing with an academic geolocated database of architecture photos, not with my vacation memories. Hence the need for a multi-level tagging system.
- On that respect, even if HomeGallery deals with metadata keywords very well, it lacks a little when dealing with hierarchical keywords (as in digiKam). I'll write you about that later.

Thank you for the great work. Please continue!
Best,
Stephen

**Comment by xemle** [comment]
Hi @asitemade4u. Thank you so much for your inputs, your workflow and the other tickets. Today I will answer only this ticket. At the weekend there is time for the other opened issues.

Thank you that HomeGallery has some place in your workflow :-)

The search box on the tag list should not the big deal including finding partial matches and I could implement it in near future (<4 weeks) - because my tag list is also long... However I thought that an autocompletion would be better but is also more complex. The search box is a good midway in the right direction.

Regarding the multi-level tagging of digikam: I am curious how digikam exports these tags? Would you mind to share a file with exported tags in it? Maybe an xmp file? And you said that you would describe your usecase of hierarchical keywords in more detail but I miss it so far ;-)

CU

**Comment by asitemade4u** [comment]
Hi @xemle , I just found yet another reason to use HG instead of PhotoPrism...: your product reads metadata in BOTH the image file and the accompanying `xmp` file, which PP often fails to do...
So:
- Thank you for considering the searchbox, it is simple and efficient
- Do not worry about hierarchical tags. I use them because I have so many of them, and also because digiKam's tagging system is kept in sync with our overall tagging system (meaning the tags we use for our research and Web publishing).
- The data structure digiKam uses for tags (in the MySQL database one can use) is fairly standard:

![image](https://user-images.githubusercontent.com/11460106/169294451-70b75060-1cb1-47ce-b03c-75ca71e0baee.png)

and I attach an `xmp` file sample -- I had to change the extension because GitHub does not accept `xmp` files as attachments.
As you can see:
- I have used darktable upstream to enhance the picture
- digiKam effectively exports tag hierarchies in the `XMP` file, e.g.:
```
 <digiKam:TagsList>
    <rdf:Seq>
     <rdf:li>GWD</rdf:li>
     <rdf:li>CEM/cem_styles+themes/cem_fence</rdf:li>
     <rdf:li>BRO/Brooklyn</rdf:li>
    </rdf:Seq>
```
Here:
- `CEM` is level 1
- `cem_styles+themes` is level 2
- `cem_fence` is the keyword

Hope this helps make HG an even more outstanding product!
S.

[_DSC5362.jpg.txt](https://github.com/xemle/home-gallery/files/8729116/_DSC5362.jpg.txt)

**Comment by xemle** [comment]
OK. Thank you for the update. So a hierarchy tag is stored by slashes as `CEM/cem_styles+themes/cem_fence` - interesting. I would prefer the slash syntax, too.

And it is good to know, what database (schema) digiKam is using.

As far I understood you you use HomeGallery only as viewing and search layer for your digital assets. First you polish your images via darktable, than you organizing them via digiKam and than you share them via HomeGallery. Nice and thank you.

Regarding the your valuable input and your opened issues: Do you know someone who can give practical support and help out to write PRs? The problem here is that currently the HomeGallery is a one-man-show on his spare time desk. So I would like to help you out more but can not offer a lot of time. Do you have any suggestions?

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
