### ISSUE TITLE
[improvement] Implement panning

### ISSUE THREAD

**Issue by asitemade4u** [xemle/home-gallery#34]
When dealing with huge sized photos (e.g. Historic maps), it would be great to be able to pan and zoom the image without having to go back to its reduced display, and double click.
I would recommend [OpenSeaDragon](https://openseadragon.github.io/) as the best open source library to achieve the result.

**Comment by xemle** [comment]
That is a nice feature. Since it targets not exactly my vision it could be awesome for me for some panorama views or sphere images of my DJI drone.

Currently there are many other issues to fix before supporting such feature. Anyway PRs are welcome ;-) 

Also here a defined plugin API would might help to easy extend HomeGallery for such needs and the plugin API needs to be implemented first, too. What a pity.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
