### ISSUE TITLE
Missing timeline to jump in time

### ISSUE THREAD

**Issue by darrepac** [xemle/home-gallery#43]
Hello

As said previously here #6 , your gallery is really nicely done and one of the best I have tested so far (I tested all of them! :) ).
It is really fast with slick design with infinite scrolling which most of the others failed to do.
Yet, in **my** opinion, a major element is missing: the capability to jump in time easily.

You would need a side timeline, plus some time in the photo stream (year/month)
Google photo, Onedrive and others big ones are providing it and it is missing to Home Gallery.

Google photo screenshot:
![image](https://user-images.githubusercontent.com/7128994/176198849-826bc093-3d08-4d5a-b9b1-d1a7ecc3c66e.png)

Onedrive screenshot:
![20220628_135532000_iOS](https://user-images.githubusercontent.com/7128994/176198938-583ae195-687c-49d8-96fc-3f9c871de33b.png)

**Comment by xemle** [comment]
Thank you so much for the flowers. I am very happy, that the HomeGallery is a serious web gallery and can compete with others alternatives.

Your proposal is very nice and I like it. Esprcially it would fit to the endless photostream.

The problem is unfortunately limited to the current available resources. This feature is not simple and has some complexity. In the meanwhile I recommend to use the year view or the search input to switch quickly to other times.

**Comment by xemle** [comment]
Hi @darrepac 
Hi @asmaps
Hi @Todd1561

Since @Todd1561 convinced me that the timeline scrolling is a main navigation method for the photo stream I spend some time on this feature. You all requested this feature and I kindly ask you to review the sneak preview on my [demo web photo gallery](https://demo.home-gallery.org). When ever the stream is ordered by time, the overview appears on fast scrolling so that you are able to navigate more precisely in time.

Please do not hesitate to give some feedback on the timings of appearing and disappearing, desktop vs mobile handling, layout, etc. 

If you like to check it out on your gallery, please download the unstable version from https://dl.home-gallery.org/dist/unstable/feature-stream-scrollbar for your platform.

**Comment by darrepac** [comment]
It doesn’t work well on my iphone but the idea behind is great!… needs to be polished!

**Comment by xemle** [comment]
> It doesn’t work well on my iphone but the idea behind is great!… needs to be polished!

Thank you for your time and your quick response.

Unfortunately I do not own an iphone or any other Apple device. I am testing on a Linux and Android device with Firefox and Chrome/Chromium. My assumption is if it is working on these browsers it should work for Apple browsers, too.

Further, I do not have a photo setup on Google photo. So my implementation is an interpretation of the provided screenshot only.

Would you mind to describe in detail what is not working? What is your expectation? Is there a problem the functionality in general? Is the UI not behaving well? Do you face performance issues?

I ask you kindly to check again, maybe reload the page to avoid caching issues of an older version? Maybe check the feature on an other device or browser?

**Comment by Todd1561** [comment]
@xemle  Thanks so much for tackling this, it'll be a welcome feature to many no doubt.  I have the same problem as @darrepac when running on my iPhone.  The slider appears and when you begin to move it the timeline appears but the slider button just jumps from top to bottom of the screen.  It seems to work fine on Chrome on Win10.

**Comment by darrepac** [comment]
I gave a quick test on chrome under ios, not working much better… 
I am on vacations but I can test deeper later on

**Comment by xemle** [comment]
Thank you for your responses and your error descriptions.

I did a blind update on device height calculations. Since I do not own an iphone I can not check it but the change is published on the [demo gallery](https://demo.home-gallery.org). Please have a quick cross check. Otherwise I will ask around for a test device.

**Comment by xemle** [comment]
Thank you @Todd1561 for the test.

So there is an issue with Apple devices which will be tough to fix since I do not have a Apple test device. I guess I need to find out which methods to use for reading viewport dimensions and setting scroll positions, since the basic functionality is there (for other vendors ;-) ) Someone told that Safari is the new IE and it fits in this case.

The other question is the required feedback from a supported browser/device if it fits the standard Google users need. Of someone can provide that, please leave a note here.

**Comment by bridadan** [comment]
Wow this is great! Tested it on my home PC and my Android browser. Definitely a welcome feature as someone attempting to migrate away from Google Photos!

**Comment by asmaps** [comment]
Tested it with Brave on the desktop and Android, works well. Nice works and super useful feature! Can't wait for it to be released :-)

**Comment by xemle** [comment]
Thank you @bridadan  and @asmaps for your positive feedback on non iOS platforms. Since I struggle with fixing on iOS devices I guess I will release quite soon this feature. The fix of iOS comes later.

**Comment by xemle** [comment]
@darrepac and @Todd1561 I guess the problem is only on iOS devices - Safari or Chrome does not make a difference here. The problem is the touch move event and catching the coordinates relative to the viewport for the timeline handle calculations. IMHO iOS behaves different than other devices.

I tried to catch some debug log through [browserstack](https://www.browserstack.com) and got some insights. The web UI of browserstack is good in general but lags in detail for the scrolling part which needs to be very responsive. So I was not able to catch the cause and will postpone this fix

If you have any suggestions, please do not hesitate to speak up.

**Comment by darrepac** [comment]
You need to find a friend with iOS device ;)

**Comment by xemle** [comment]
> You need to find a friend with iOS device ;)

Well, I need a friend with a spare iOS device. But I will have a look at that on a later stage. First I am releasing version 1.6.0 with this feature for non iOS devices.

@bridadan and @asmaps please test this feature in the new feature. If you are facing any non-iOS related issues, let me know.

**Comment by bridadan** [comment]
Just deployed 1.6.0, working great!

**Comment by xemle** [comment]
Thank you very much. Enjoy

**Comment by xemle** [comment]
@darrepac I had the change to debug the issue with an iPhone. But I was not able to fix it within 3 hours and I am running out of ideas how to fix it. I was able to improve it and could reduce the screen flickering but it is still there and it's annoying.

However, I found out that you can use the (tiny) system/native scroll handle and with it the scrolling works fine. Could you check if the system handle could be an acceptable workaround?

**Comment by darrepac** [comment]
> @darrepac I had the change to debug the issue with an iPhone. But I was not able to fix it within 3 hours and I am running out of ideas how to fix it. I was able to improve it and could reduce the screen flickering but it is still there and it's annoying.
> 
> However, I found out that you can use the (tiny) system/native scroll handle and with it the scrolling works fine. Could you check if the system handle could be an acceptable workaround?

Is it implemented in your demo gallery? If yes, I did not see any noticeable improvment I am sorry.
In the meantime, I move to synology photo station, and it is smooth and quick! But I don’t know the technology behind.

What do you mean by « (tiny) system/native scroll handle »?

**Comment by xemle** [comment]
@darrepac thank you for the quick reply

I did not updated the demo but now it is including my quick fix 

> In the meantime, I move to synology photo station, and it is smooth and quick! But I don’t know the technology behind.

Glad you found your solution with synology. If you find the technology behind it, please let me know ;-)

> What do you mean by « (tiny) system/native scroll handle »?

On my test device the native scrollbar is visible on scrolling. It is a bit tricky to touch and activate it but if it is active the scrolling is smooth.

**Comment by darrepac** [comment]
Here is what I have

**Comment by xemle** [comment]
Thank you very much @darrepac for the video, the insights and your time. I am sorry that this issue on iOS could not solved easily. I had a similar behavior but not that high frequent jittering.

Up to now I do not know why iOS is flickering and the scroll position is jitter while scrolling. The touch events are also quite strange.

Here are some technical values for reference:

```
20:44:11.031 Touch move: client 291,7491, page 291,10243, scrollY 2752. pos 291,7491
20:44:11.061 Touch move: client 291,146, page 291,10246, scrollY 10100. pos 291,146
20:44:11.034 Touch move: client 291,145, page 291,10245, scrollY 10100. pos 291,145
20:44:11.075 Touch move: client 291,-7198, page 291,2902, scrollY 10100. pos 291,-7198
20:44:11.132 Touch move: client 291,154, page 291,2906, scrollY 2752. pos 291,154
20:44:11.113 Touch move: client 291,-66, page 291,2903, scrollY 2969. pos 291,-66
20:44:11.142 Touch move: client 291,372, page 291,3124, scrollY 2752. pos 291,372
20:44:11.186 Touch move: client 291,-6556, page 291,3125, scrollY 9681. pos 291,-6556
20:44:11.199 Touch move: client 291,158, page 291,3127, scrollY 2969. pos 291,158
20:44:11.223 Touch move: client 291,6872, page 291,9841, scrollY 2969. pos 291,6872
20:44:11.279 Touch move: client 291,-314, page 291,9842, scrollY 10156. pos 291,-314
20:44:11.209 Touch move: client 291,159, page 291,3128, scrollY 2969. pos 291,159
20:44:11.329 Touch move: client 291,-312, page 291,9844, scrollY 10156. pos 291,-312
20:44:11.320 Touch move: client 291,-313, page 291,9843, scrollY 10156. pos 291,-313
20:44:11.376 Touch move: client 291,164, page 291,9845, scrollY 9681. pos 291,164
20:44:11.460 Touch move: client 291,6813, page 291,10322, scrollY 3509. pos 291,6813
20:44:11.493 Touch move: client 291,6814, page 291,10323, scrollY 3509. pos 291,6814
20:44:11.541 Touch move: client 291,-6480, page 291,3677, scrollY 10157. pos 291,-6480
20:44:11.559 Touch move: client 291,169, page 291,3678, scrollY 3509. pos 291,169
20:44:11.602 Touch move: client 291,-6331, page 291,3826, scrollY 10157. pos 291,-6331
20:44:11.617 Touch move: client 291,170, page 291,3827, scrollY 3657. pos 291,170
20:44:11.637 Touch move: client 291,171, page 291,3828, scrollY 3657. pos 291,171
20:44:11.730 Touch move: client 291,113, page 291,3830, scrollY 3717. pos 291,113
20:44:11.751 Touch move: client 292,176, page 292,3893, scrollY 3717. pos 292,176
20:44:11.794 Touch move: client 292,29, page 292,3894, scrollY 3865. pos 292,29
20:44:11.813 Touch move: client 292,31, page 292,3896, scrollY 3865. pos 292,31
20:44:11.820 Touch move: client 292,179, page 292,4044, scrollY 3865. pos 292,179
20:44:11.875 Touch move: client 292,92, page 292,4046, scrollY 3954. pos 292,92
20:44:11.885 Touch move: client 292,93, page 292,4047, scrollY 3954. pos 292,93
20:44:11.931 Touch move: client 293,2736, page 293,4136, scrollY 1400. pos 293,2736
20:44:11.953 Touch move: client 293,2737, page 293,4137, scrollY 1400. pos 293,2737
20:44:11.966 Touch move: client 293,183, page 293,1583, scrollY 1400. pos 293,183
```

while `client` are `clientX` and `clientY` and `page` are `pageX` and `pageY` from the [touch event coordinates](https://developer.mozilla.org/en-US/docs/Web/API/Touch). `clientY` and `pageY` values are jumping while scrolling:

|clientY|pageY|
|--------|-------|
|7491|10243|
|146|10246|
|145|10245|
|-7198|2902|
|154|2906|
|-66|2903|
|372|3124|
|-6556|3125|
|158|3127|
|6872|9841|
|-314|9842|
|159|3128|
|-312|9844|
|-313|9843|
|164|9845|
|6813|10322|
|6814|10323|
|-6480|3677|
|169|3678|
|-6331|3826|
|170|3827|
|171|3828|
|113|3830|
|176|3893|
|29|3894|
|31|3896|
|179|4044|
|92|4046|
|93|4047|
|2736|4136|
|2737|4137|
|183|1583|

Currently I am excluding jumps from `clientY` events but the jittering of the scrollbar and the view stays.

An Android this behavior does not appear. Very frustrating.

**Comment by xemle** [comment]
Hi @darrepac 

yesterday I had a recent iPhone of a colleague in my hands and tested the demo page. There was no flickering on Safari. ... and it worked on chrome. On [browserstack](https://browserstack.com) it seems to work, too. 

So I am bit puzzled what is the current state. Maybe you have an caching problem. Could you check again after you cleared the cache of the demo page? It would be awesome if this iOS issue could be solved.

**Comment by xemle** [comment]
Awesome!

@darrepac thank you so much for your availability, time and feedback.
