### ISSUE TITLE
"gallery init --source /pictures" acts strangely 

### ISSUE THREAD

**Issue by timdonovanuk** [xemle/home-gallery#45]
1. Fresh install
2. Have config set to default
3. Run ./gallery init --source ~/pictures
4. End up at the interactive shell (?)
5. Init doesn't actually run

**Comment by timdonovanuk** [comment]
In general --source seems to completely disregard the path passed to it. I created a folder at /pictures, and it doesn't seem to ever import from there if i I do --source /pictures

**Comment by xemle** [comment]
Thank you for trying HomeGallery and for open your questions here.

Could you give some more details to your environment, e.g. OS, do you run the binary or Docker version? Where are your media files stored? Where did you installed/downloaded HomeGallery? What is your working directory?

```
./gallery init --source ~/pictures
```

should be 

```
./gallery run init --source ~/pictures
```
as stated in the [docs](https://docs.home-gallery.org/install)

`./gallery init --source ~/pictures` will start the interactive shell because no valid `init` as primary command is found. Further in Bash `~/pictures` should be expanded to `$HOME/pictures`. It is different to `/pictures` which is expected to be at your system's root.

Have you viewed/checked your `gallery.config.yml` for documentation comments. Maybe you find ideas for your causing problems there?

**Comment by xemle** [comment]
@timdonovanuk Could you solve your issues?

**Comment by xemle** [comment]
I am closing this ticket due inactivity. Please do not hesitate to reopen it
