### ISSUE TITLE
feature request: add button to import pictures

### ISSUE THREAD

**Issue by ElFishi** [xemle/home-gallery#46]
Would be nice to have a button on the web interface that runs the run import --update command to add more pictures to the database. 
That way pictures freshly added to the drive can be published immediately.

**Comment by xemle** [comment]
Thank you for this request.

My proposal is to support a list of actions for the UI which can be configured in the the `gallery.config.yml`. One action could be to run the import command - another could be to call the cast or the fetch command.

So in a draft there would be

* general actions such as import or fetch
* current list view action such as casting
* current single media action such as printing

Would that fit to your needs? Do you have additional ideas?

**Comment by ElFishi** [comment]
Not sure what fetch does: is it to get pictures from a second hg server? 

In any case, it is a good idea to make more possible actions configurable.

You could, of course, add more items (like path to source directory) to be configurable idally even via the web interface. 
But that would only add convenience, not funcionality.

**Comment by xemle** [comment]
> Not sure what fetch does: is it to get pictures from a second hg server?

Yes. You can import/sync media from another instance and can apply also an query filter to import a subset.

I do have an NAS with all the original media files and the main gallery A. But for convenient the gallery A is served on an other device (Raspberry Pi). The clone is done via the fetch command. Further a third gallery B is responsible to create the newest pictures from the smartphone which are updated from time to time. The fetch command pulls B into A.

... you know - eat your own dog food ;-)

> In any case, it is a good idea to make more possible actions configurable.
> 
> You could, of course, add more items (like path to source directory) to be configurable idally even via the web interface. But that would only add convenience, not funcionality.

Exactly. I did not found time so fare to get this done. Do you have abilities to implement that? PRs are welcome :-D

**Comment by ElFishi** [comment]
I'd love to lend a hand, but this is way beyond my capabilities. 
But out of curiousity, where would be the sections to look at in order to add such features?

Thank you so much for the work you put in already.

**Comment by xemle** [comment]
> But out of curiousity, where would be the sections to look at in order to add such features?

There are 2 big changes for this request for me:

* Read `gallery.config.yml` in the server command instead of using only args. Currently the CLI reads the config and creates args for the server command. Since more and more options are arriving it is good to read the config in the server command. This would also help to enrich the config with the requested command like update - but also gives the ability to enrich the user definitions for login token or filter query.
* Add a main menu to the UI to create space for the requested update action. I imagine a side menu on the left.

Than you need to define the space and format in the config, read that in the server, pass the action names to the webapp, list the actions in the menu, pass the user selected action to the server, create an api to receive the action, perform the action and you are almost done. Test it, write tests, update docs, release. Any questions?  ;-)

> Thank you so much for the work you put in already.

Thank you soo much

**Comment by xemle** [comment]
While there is no update button yet, the latest master contains changes to watch the source directories for changes and triggers an import automatically if somethings changes.

After some broader tests I will make a release with this change

**Comment by xemle** [comment]
Since [v1.10.0 - 2023-06-13](https://docs.home-gallery.org/changelog.html) the server is watching for new files an import them automatically.

Closing this issue due inactivity. Please do not hesitate to reopen it if required.
