### ISSUE TITLE
Images are missing after initial import, API is disabled

### ISSUE THREAD

**Issue by Gulluth** [xemle/home-gallery#49]
Running in docker-compose on Debian 11.4 x86_64

I disabled the API in docker-compose, and modified the API URL as per the comment here:
https://github.com/xemle/home-gallery/issues/37#issuecomment-1167898665

I also removed the volume data from my first indexing, and started importing the photo archive fresh. The import is a lot faster without the API, however most of my images have broken URIs for the thumbs and full sized images, as can be seen in the attachment.

I checked in incognito mode, to ensure this isn't a caching problem and I have the same results. Is there a way to regenerate all of the thumbnails, or do you have advice on how I can resolve this issue?

![image](https://user-images.githubusercontent.com/1114761/184959022-802c1dc9-8365-41ce-81ee-3a6be53da7c8.png)

**Comment by xemle** [comment]
Mm. Currently I have no idea why the images are not shown. Maybe you are using the old database?

If you want to disable a feature like object detection afterwards but not want to throw away all the thumbnails or videos, you need to delete all `*.cache` files in the storage and corresponding feature files. For the object and face detection it would be

```
cd <storage dir>
find -name '*.cache' -name '*-faces.json' -name '*-objects.json' | xargs rm
```
NB: The `.cache` files are per directory, the `faces` and `objects` are per image. I assume that the similarity might be still handy so I do not delete them in the given example...

Afterwards you can rebuild the database via the interactive shell through "System" and than "Rebuild database"

```
./gallery.js 
✔ Gallery main menu · system
? System options … 
  Show expanded configuration
  Debug extractor
▸ Rebuild database
  Back
```

If this does not help or is not handy, you can start the import as you described and after the completion you delete the database file and rebuild it via the `update` command without `--initial` or `--update` parameter. 

This procedure is save since the database can be recalculated while the events are critical due the manual tagging steps. See [internals](https://docs.home-gallery.org/internals) if you are interested in.

Please let me know if this helps

**Comment by Gulluth** [comment]
> Maybe you are using the old database?

Nah, I deleted the whole directory and remounted the NFS mount for the images from my NAS.

Thanks for those additional steps, I will go ahead and close this issue and do some more testing on my end.
