### ISSUE TITLE
Datenschutz anpassen.

### ISSUE THREAD

**Issue by ChR-iSz** [xemle/home-gallery#53]
Hallo Sebastian, 

ich sehe in Deinem Profil das du aus Deutschland kommst. Würde daher in deutsch schreiben.

Erstmal danke für die tolle Software. Sehr gute Arbeit.

Mir liegt allerdings eines quer im Magen:

Wenn man die Anleitung für Docker durchgeht (denke das gillt auch für lokale Installationen), wird die gallery.config.yml erstellt. Soweit so gut.

Die Extractor settings sind default in der config "**Auskommentiert**" (!), welches bedeutet sollte, das der Extractor deaktiviert sein sollte. Dem ist aber nicht so! Die Bilder werden an: **https://api.home-gallery.org** gesendet. Was dort damit passiert, ein Rätselraten ?!  -> Ein absolutes No-Go.

Es findet sich zwar ein Hinweis auf https://docs.home-gallery.org/api-server/index.html, allerdings wird nicht erwähnt, das das Übermitteln an Deinem Server default eingeschaltet ist, auch wenn der extractor explizit auskommentiert ist in der config.

Ich Bitte Dich dies zu beheben, und einen auskommentierten extractor  in der config entweder zu deaktivieren (wie erwartet), oder irgendwo einen "dicken" Hinweis zu hinterlassen, dass der extractor immer default eingeschaltet ist, und Bilder an Deiner URL leitet.

Viele Grüße Christian

**Comment by xemle** [comment]
Hi @ChR-iSz 

thank you for finding this project and open your privacy concerns here. Since the privacy concerns is not limited to Germans I reply in English.

I understand your concerns about the public API service. The split between the "core" and the API service was born out of local requirements and comes with pro and cons. In the FAQ [What data is requested from public services?](https://docs.home-gallery.org/configuration/index.html#full-configuration) describes also the functionality.

In the [default configuration](https://docs.home-gallery.org/configuration/index.html#full-configuration) it is written how comments and default values are defined:

```
# HomeGallery configuration file
#
#
# Default configuration file is gallery.config.yml. JSON format is
# also supported (gallery.config.json)
#
# This is a comment, starting with hash tag and space ('# ')
# A default value starting with hash tag and variable ('#baseDir...')
```

So 

```
#
# Extractor settings
#
#extractor:
  # Api Server is used for image similarity, object and face detection
  #apiServer:
  #  url: https://api.home-gallery.org
```

says by default it uses the public service.

Further for the [docker compose](https://docs.home-gallery.org/install/index.html#docker-compose) setup it states that it uses an local API server.

Regarding the public API service `https://api.home-gallery.org` it is just the [public docker image](https://hub.docker.com/r/xemle/home-gallery-api-server) on my public machine. This service does not save any data. It would be the opposite of the whole idea and motivation of the project: To keep your data local and private...

Remains the question of trust: You can believe what is available as documentation and code - or you can be skeptic (which is totally fine with me). Since it is open source you can look on this Github repo, read the code, open an issue or even better create an PR at the [documentation repo](https://github.com/xemle/home-gallery-doc) to improve and clarify your concerns ;-) Maybe your change in the documentation fits better than mine so far.

> Erstmal danke für die tolle Software. Sehr gute Arbeit.

Thank you. I hope it can help to browse your pictures

Thanks again for your time and effort to improve this project

**Comment by xemle** [comment]
Hi @ChR-iSz 

did my response help? Do you have further questions?

> irgendwo einen "dicken" Hinweis zu hinterlassen

Where or when do you exactly expect a warning if the public API server is used? There could be several places:

- On the [homepage home.gallery.org](https://home-galery.org)
- Somewhere else in the documentation
- In the logs when extractor is starting

Do you have other your ideas or preferences?

**Comment by ChR-iSz** [comment]
Hi Sebastian,

Thank you for your answer.

A warning message in the logs would certainly be useful (info-log).

But I still suggest (of course your project, and your decision) to disable the extractor by default for your submission.
Would like to see an enable: true/false in the config file, which defaults to false. Then below that the URL where the requests are sent.

Should a user set the enabled value from false to true it should be obvious in the next line where the requests are going. Especially since the user has then consciously activated the function.

Only as a suggestion.

**Comment by xemle** [comment]
> A warning message in the logs would certainly be useful (info-log).

This option can be done and will consider it in the near future to implement that.

> But I still suggest (of course your project, and your decision) to disable the extractor by default for your submission.

For my usecases and also as project main feature the results of the API server are important. So to disable it by default would break these from the start.

IMHO due the basic project properties (open source, self hosted, project size and members) it is justifiable to read the doc in advance and get familiar with its feature set and detect the circumstances with the API server.

So the current state with public API server enabled by default for non docker version is fine with me.

It is technically possible to include the API server into the default app bundle and start and stop it when the extractor runs. Back than it was not due the lacking wasm support of tensorflowjs which is now supported.

I would prefer to go that way first than disable the API server by default. This feature needs some time to implement and PRs are welcome for it.

> Only as a suggestion.

Thank you for your proposals. I hope I could highlight my desicions. Futher input, discussion and ideas are welcome

**Comment by xemle** [comment]
Hi @ChR-iSz 

since the fresh release v1.7.0 the extractor logs a warning if the public API server is used:

```
You are using the public api server https://api.home-gallery.org for similar images. Please read its documentation at https://docs.home-gallery.org for privacy concerns
You are using the public api server https://api.home-gallery.org for object detection. Please read its documentation at https://docs.home-gallery.org for privacy concerns
You are using the public api server https://api.home-gallery.org for face detection. Please read its documentation at https://docs.home-gallery.org for privacy concerns
```

**Comment by cimba007** [comment]
Hello. Although this topic is more then a year old .. i still have trouble with this.

I tried to disable the api with:
```
  apiServer:
    url:
    timeout: 30
    concurrent: 5
    disable:
      - similarDetection
      - objectDetection
      - faceDetection
```

.. still .. even after deleting the database .. all images get object-detection run all over the place. 

I can only agree, that all features involving some online APIs should be disabled by default for privacy conserns.

Best regards Marc

**Comment by xemle** [comment]
Hi @cimba007 

> Hello. Although this topic is more then a year old .. i still have trouble with this.

Thank you for your voice and your input.

> I tried to disable the api with:
> 
> ```
>   apiServer:
>     url:
>     timeout: 30
>     concurrent: 5
>     disable:
>       - similarDetection
>       - objectDetection
>       - faceDetection
> ```
> 
> .. still .. even after deleting the database .. all images get object-detection run all over the place.

If you just delete your database the storage might still contain files from previous api server calls and will use them. The extractor should not call the api service on new files.

Your described setting is checked in an [E2E Test](https://github.com/xemle/home-gallery/blob/master/e2e/specs/extractor/api-server.md#disable-api-server-features) and should work as expected and as designed.

> I can only agree, that all features involving some online APIs should be disabled by default for privacy conserns.

I can understand that privacy is very important for us. Therefore there is information about the public usage of these requests in the documentation and a warning message in the logs. 

For me I can ensure that the public service https://api.home-gallery.org is nothing more than the docker version from the docker hub. This fee service is there for convenience for low powered devices such Raspberry PI, for non-docker environments or quick evaluations of the gallery. Since there is no data storage for the images on the public service I leave the decision to the user to trust it or not. As you need to trust the code or not. It is your free choice.

To disable it by default is not an easy question to answer. For a docker-compose these feature detection should be enabled. Maybe for other setup not. However I see these features as convincing features to use  HomeGallery over other similar software so I would like to present these features by default. I am just loving the similarity feature which I want to present to others.

You are welcome to contribute your option as PR on the docs or the code. One valid possibility is to print a warning for a public api server usage at configuration initialization, too.

What do you think about this idea and what do you think you can contribute to it? Would you mind to improve the docs so that it meets your expectation? How about some code changes?

**Comment by cimba007** [comment]
Thank you for your time to elaborate on this topic. I understand that this might be a feature that sets home-gallery apart from other software. I find documentation a little bit problematic as . "you could just simply ignore it". Might it be a possibility to integrate a popup on the first startup of a fresh instance and let the user decide on what feature to enable? This popup might be configured in such a way, that it is only shown incase the setting is not altered from the default setting? If the user "enables" or "disables" the feature in the config file the popup will not be shown. Its just an idea to make it more obvious. I understand that there is already a info added in the logfile but .. tbh. .. the logfile contains so many information that it might be overlooked.

For the seconds question .. "If you just delete your database the storage might still contain files from previous api server calls and will use them. The extractor should not call the api service on new files." Can you elaborate on where this information might be retained so I could test it by deleting whatever file/service might still containe this information?

Thank you for making this great tool available to the public!

Best regards

**Comment by xemle** [comment]
> Thank you for your time to elaborate on this topic. I understand that this might be a feature that sets home-gallery apart from other software. I find documentation a little bit problematic as . "you could just simply ignore it". Might it be a possibility to integrate a popup on the first startup of a fresh instance and let the user decide on what feature to enable? This popup might be configured in such a way, that it is only shown incase the setting is not altered from the default setting? If the user "enables" or "disables" the feature in the config file the popup will not be shown. Its just an idea to make it more obvious.

Currently a popup is not easy to implement and the UI has no knowledge about the configuration. Further there is no acknowledge dialog to handle and store this state and users decision.

As suggested before I could image to add a warning while the configuration is initialized on the setup procedure (`gallery run init --sources ...`). There could be also an option to enable/disable the api server calls. IMHO it should be enabled by default but the docs can mention this option for privacy concerns.

As the software is open I suggest to provide this change by a PR from you or someone else. I am currently working on other features which consumes my time which is available for this spare time project. If required I can assist with guidance to implement that.

> I understand that there is already a info added in the logfile but .. tbh. .. the logfile contains so many information that it might be overlooked.

Yes and no. Warnings are rare. This is a warning message and should be as clear as a log entry can be.

I think you can also check the docs and try to emphasis this privacy concerns as PR for documentation improvement.

> For the seconds question .. "If you just delete your database the storage might still contain files from previous api server calls and will use them. The extractor should not call the api service on new files." Can you elaborate on where this information might be retained so I could test it by deleting whatever file/service might still containe this information?

Just add a new file and check if these files are present on the next import (also the logs should not mention anything about a call).

Or delete the file from the api server. The storage directory contains different raw output files also from the api server:

```
./25/d7/b73c43674fec76979c2fef7d09884c1864af-exif.json
./25/d7/b73c43674fec76979c2fef7d09884c1864af-objects.json
./25/d7/b73c43674fec76979c2fef7d09884c1864af-faces.json
./25/d7/b73c43674fec76979c2fef7d09884c1864af-image-preview-1280.jpg
./25/d7/b73c43674fec76979c2fef7d09884c1864af-image-preview-1920.jpg
./25/d7/b73c43674fec76979c2fef7d09884c1864af-image-preview-800.jpg
./25/d7/b73c43674fec76979c2fef7d09884c1864af-image-preview-320.jpg
./25/d7/b73c43674fec76979c2fef7d09884c1864af-vibrant.json
./25/d7/b73c43674fec76979c2fef7d09884c1864af-similarity-embeddings.json
./25/d7/b73c43674fec76979c2fef7d09884c1864af-image-preview-128.jpg
```

You can delete the `*-objects.json`, `*-faces.json` and `*-similarity-embeddings.json` files and rerun the (full) import. But I do not see a benefit to delete these files since the files were already transmitted to the api server and it wont change the misconfiguration from the past.

> PS: Maybe something even more easy .. provide simpley two "sample" config files .. one maybe with _privacy that has some stuff preset by default. This might be an easy "quickwin" to solve this and make everbody aware that it can be configured.

As stated before: Please provide a PR. I guess the initialization of the configuration is a good part to implement this privacy requirement.

> Thank you for making this great tool available to the public!

You are welcome.

Final question: Do you have the possibility to run the api server locally via docker? So you can benefit from this feature? Or why would you like to disable these feature?

**Comment by cimba007** [comment]
Next problem .. it seems you can't disable the geoReverse feature?!
```
  geoReverse:
    url: 
  #   Preffered address language of geo code reverse lookups
  #   addressLanguage: [de, en-US] # for multiple languages
  #  addressLanguage: [en, de]
  # excludes are using gitignore patterns
  excludes: ['*.*']
```
I still get ..

[2023-12-27 00:09:11.730]: extractor.geoReverse warn Invalid geo position values of 745c996:REDACTED.jpg: 0 0
[2023-12-27 00:09:12.732]: extractor.geoReverse warn Invalid geo position values of b127ff7:REDACTED.jpg: 0 0

shouldn't exclude .. like .. exclude all files?

Thank you for your patience in advance :-)

**Comment by xemle** [comment]
> Next problem .. it seems you can't disable the geoReverse feature?!

This feature is not implemented yet. PRs are welcome. You can add an invalid URL like `http://localhost:1025` for the geo reverse feature. I do not know by heart what happens on a invalid URL. I do not know if always a warning message is printed or if it is printed only some times at the beginning.

@cimba007 since you are comment on this thread it seems that you are concerned about any external calls. It would help me to understand you if you explain your requirements and your needs so we can discuss  them. We can further evaluate if your concerns fit the current design of HomeGallery in general. Currently I feel a bit lost to provide appropriate help.

**Comment by cimba007** [comment]
@xemle Okay .. so let me elaborate my usecase for home-gallery. I currently have an collection of private photos .. something like 150gb. Its not feasable to make them available to my family for easy viewing. My idea was to self-host them on my private computer. I don't want any of the photos to be made available to any sort of cloud service. They are private and I don't want them somewhere on the internet as I don't trust any 3rd party withi this kind of private information.
 
I might make the gallery accessible via Internet and and user/password feature but it would also be a possibility to use a VPN on the phone to directly connect to my home-computer.

Currently the files are sorted in folders like "2010 NameOfEventOrTopic". There is a total of 350 such folders.

I like the idea of the timeline but would also appreciate just a listing of folders. Maybe this can be solved by using the "Tag" feature by tagging all files withan an folder with the "Foldername".

I don't need the gea-feature as non of my photos has GPS information attached. 

Furthermore I understand, that the API-Feature would provide some benefit, as it might allow me to quickly filter for all "cat" photos, in case the classification is able to classify cats. For this I understand that I would have to setup an private instance of the API server (same as running in the docker-container on your end). For this I want ot better understand how to use docker but for now I stick with the Windows-Standalone version that I can run by console.

As I said before I have concerns with sending all my family photos (even if in a small/compressed form) to through some 3rd party application. I don't think that you have an evil intent but the most probable cause for a data breach might be some outdated security feature - nevertheless - I have limited trust.

I appreciate home-gallery so far as getting it running with Windows was easy enough. Now I can scan my library and check if it is the right tool for this.

Furthermore I don't need any advanced features as the user of the library would most probably family members that just want "to watch" some memorys. For this I like the basic interface.

For now I have commented out the function-calls

From this "known startpoint" I would like to make some progress in getting docker running and maybe even enable the detection features .. but as this is only an added "Bonus" I would do it exactly in this order. As you already meantinoned. If the photos are once processed (over the cloud) there is no benefit in disabeling it afterwards.

```
      // single ungrouped entries
      imagePreview(storage, extractor),
      //videoPoster(storage, extractor),
      vibrant(storage, extractor),
      //geoReverse(storage, config),
      logPublicApiPrivacyHint(config),
      //similarEmbeddings(storage, extractor, config),
      //objectDetection(storage, extractor, config),
      //faceDetection(storage, extractor, config),
      //video(storage, extractor, config),
      //.pipe(videoFrames(storageDir, videoFrameCount))
```

Thank you for taking your time to follow this thread. 

In addition I have never programmed in javascript/phython beyond an "hello world". Most of the time I code and C# and the hurdle for me to make myself familiar and provide an PR is just too huge at the moment.

Thank you again, best regards

**Comment by xemle** [comment]
@cimba007 thank you for your detailed response and motivation to use HomeGallery

> I like the idea of the timeline but would also appreciate just a listing of folders. Maybe this can be solved by using the "Tag" feature by tagging all files withan an folder with the "Foldername".

While this feature requests raises from time to time I have not implemented it since I do have unordered folders. The default search honors the folder name so maybe you will find your images quickly by type some search input terms.

> I don't need the gea-feature as non of my photos has GPS information attached.

What a petty since they are also a nice search vector and this feature comes for free with photos taken from mobile phones. And since the best camera is the camera which you have at the moment of the shot the mobile phone wins quite often in recent years.

> Furthermore I understand, that the API-Feature would provide some benefit, as it might allow me to quickly filter for all "cat" photos, in case the classification is able to classify cats. For this I understand that I would have to setup an private instance of the API server (same as running in the docker-container on your end). For this I want ot better understand how to use docker but for now I stick with the Windows-Standalone version that I can run by console.

You can run api-server via docker in WSL. It should work. It is also possible to clone/download the repo and run the api server from the command line via a node environment.

Up to now there was not a big deal with the api server. So there is also no generic bundle for the api server like the gallery. Currently that would be possible but I wish the api server serves more and updated ML/AI feature detection. Using docker the used technology (node, python, go, etc) can be hidden within the container. If I provide a binary for the api server it can be a deal breaker in the future.

Summary: The api server works somehow and it does not get a lot maintaining attention. It is basically the version from the beginning of 2021. So you are welcome to improve that.

> For now I have commented out the function-calls

Awesome. That is a good approach at the moment. Congratulations that you found your way to your requirement.

> In addition I have never programmed in javascript/phython beyond an "hello world". Most of the time I code and C# and the hurdle for me to make myself familiar and provide an PR is just too huge at the moment.

But at least you are familiar with coding and you can comment out stuff. That is great.
