### ISSUE TITLE
Issues with static export: Edit is possible and lots of API calls?

### ISSUE THREAD

**Issue by Kovah** [xemle/home-gallery#54]
Hi! I would love to use home-gallery for a public photo gallery.

However, after fiddling for like an hour, I cannot get the export working as expected. There are two issues:
- No matter which settings I change, the static export always shows the "Edit" functionality. When visiting your demo, there is no such edit button. How do I get rid of it?
- When clicking any image, the site sends requests to `/api/events.json` and `/api/events/stream`, which all fail because there is no such directory in the export. I have found some places in the documentation where events are mentioned, but without any details about generation or how to enable/disable them.

If I can post any more details, please let me know. I am using the Docker image to generate the database and images, and to export the static files.

**Comment by xemle** [comment]
Awesome that you are using the gallery and the export functionality. Thank you for reporting your issue.

The behavior what you are describing is: It is working as designed. The edit mode/action is currently also available in the export and will lead to a "dead end" for the customer.

It can be discussed if it is a bug or a feature. It is a bug to produce 404 in server logs, it could be a feature to test tagging also on read only mode.

IMHO I woud like to open a discussion what is the general need and your need. So to understand you better, what is your use case and expectation for the export feature?

Mine is to create a demo page and to provide the full frontend freature with tagging. Also I do some exports for some family events.

**Comment by Kovah** [comment]
Thanks for your extensive answer. Good to know that "it's not my mistake". 😄 
Personally, I would like to use the gallery to have a public gallery of my pictures that I do not post on Unsplash. Most photo galleries are quite heavy (large backend), do not allow viewing photos without login, or just look terrible, that's why I like Home-Gallery so much.
When exporting the gallery, I would expect it to be completely standalone, a read-only version of the gallery, suitable for putting it on a server. Having features there that are dead ends and generate errors should be disabled.
Does that make sense?

**Comment by xemle** [comment]
> Most photo galleries are quite heavy (large backend), do not allow viewing photos without login, or just look terrible, that's why I like Home-Gallery so much.

Thank you for the flowers

> When exporting the gallery, I would expect it to be completely standalone, a read-only version of the gallery, suitable for putting it on a server. Having features there that are dead ends and generate errors should be disabled. Does that make sense?

OK. Thank you for sharing your use case.

As I said: The edit mode in the export can be a feature and it can be a bug, too.

In either cases false errors on the server side should be avoided. This is more a bug.

For the export there could be a flag to enable or disable the edit mode. So the user can decide which mode to use for the export. Default would be to disable the edit mode since I assume that is more the general expectation.

What do you think?

I believe still that an edit mode in the static export can give value for following use cases

- demonstrate the basic functionality
- tag your personal images and store the events on your browser. So a new visit you can find your stuff again (NIY)
- export your events and import them somewhere else. So you have the ability to tag images on your public gallery and later you import these changes to your private one (NIY)

And last but not least PRs are welcome.

**Comment by Kovah** [comment]
Totally understand your point. A toggle to enable/disable the edit mode in the export would be nice.

**Comment by xemle** [comment]
@Kovah The edit toggle is available since 1.8.0. See [export options](https://docs.home-gallery.org/cli/index.html#export-command) with `--edit` option.

**Comment by Kovah** [comment]
Ohhh super cool! Will try it out. Many thanks!
