### ISSUE TITLE
Purging rendered previews

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#55]
After a while, the prerender previews are not in sync anymore. Especially if you deleted some larger directories and the deleted files were removed from the database but not the cache. 
Manual removal is difficult because you can not handle the structure.

The mechanism seems to work purely additive, so that the cache "storage" gets bigger and bigger, but never smaller once images or especially videos have been removed.
Only workaround right now seems to be a full rescan after removing config and storage which can last days.

Since missing files are detected and the database knows which storage items in cache exist, maybe there could be a switch that enables deleting them automatically.

**Comment by xemle** [comment]
Hi @onyxogen

thank you for reaching out. What you describe is true. The storage grows currently by the assumption that your local disk space is cheap and you wont have much deletion. A clean up task to purge deprecated files was not implemented yet due given assumptions.

This assumption seems not to be true on your side. Could you describe your use case with Home Gallery and why it is crucial on your side that the storage should have a clean state?

BTW have you read the [internals](https://docs.home-gallery.org/internals) of the gallery to get familiar with the workflow and the data structures?

**Comment by onyxogen** [comment]
So far there have been 3 use cases: 
1. self-deleting rolling webcam videos.
2. videos from everyday life recorded in 4K / 60 fps, which are also restructured and deleted from time to time, but should be up-to-date in the home gallery.
3. (rather rarely): Import attempts of mass data, but with wrong modification dates and filenames that need reimporting. This destroys the whole order and is hard to get rid of.
Is it essential? Probably not. I just thought that since it is known for each file where its previews are in the storage, it should be easy to provide a delete option for them.

**Comment by xemle** [comment]
>     1. self-deleting rolling webcam videos.

OK. Nice that you have such videos and you are using HomeGallery for it :smile: 

>     2. videos from everyday life recorded in 4K / 60 fps, which are also restructured and deleted from time to time, but should be up-to-date in the home gallery.

Could you estimate for 1. and 2. how much space you would save if purging files is implemented? What would be the gain on your side.

I am asking because in theory this is a very nice feature. Also it could drop polluted cache files (which I have from time to time). However the estimated benefit should be discussed and I would like to solve problems not wishes to be direct. E.g. It would not make sense to implement this feature if only 1% of storage capacity will be saved. If it is 20% that is a good start.

>     3. (rather rarely): Import attempts of mass data, but with wrong modification dates and filenames that need reimporting. This destroys the whole order and is hard to get rid of.

If the content of the file does not change, HomeGallery will reuse the preview files. So it should be fine to move and rename files without changing its content. Further, it is recommended to use sidecar files such as XMP file to set or correct time.

Could you describe this use case to figure it out if the workflow or the software could be improved?

>        Is it essential? Probably not. I just thought that since it is known for each file where its previews are in the storage, it should be easy to provide a delete option for them.

Well, it is known in one direction very well: If you have a file, you can lookup it on the filesystem pretty easy. However if you are on the filesystem you have to check if it it not referenced and you need to walk over all files in the storage.

It is possible for sure however the purge command is not so trivial and I assume it will be slow for the amount of filesystem accesses.

I hope these direct questions are fine to clarify and I am happy for your valuable input.

**Comment by onyxogen** [comment]
I'm not sure that's really about 20%. Over time, the failed imports will become less and less important compared to the successful ones.

I don't find the use of the sidecar files that useful, as I would rather correct the source - and I do. I have a script that homogenizes the EXIF tags, filenames and modification dates of the photos before an import. Specifically optimized for my devices used, because each has its peculiarities unfortunately.
At the beginning I had to test which information is responsible for sorting the files. But in the meantime I have it under control.

Overall, I would say that there are more important features than freeing the memory. 
E.g. a customizable size of the thumbs or folders support instead of structuring via tags only. I sort my files into folders and with each import, I try to set tags that map the folder structure. This way I can directly select and view a "folder". It's not that elegant but it seams to work for me.

Donwloading original files and configuration of preview resolutions via yaml would be very nice too...

**Comment by onyxogen** [comment]
Oh and one simple thing drives me nuts :-)   The font that symbolizes the current thumbnail as a video is gray. Most of the time I can't even read it, it's so small and gray. I'd love to set it to white because there are barely any photos with pure white.

**Comment by xemle** [comment]
> I don't find the use of the sidecar files that useful, as I would rather correct the source - and I do. I have a script that homogenizes the EXIF tags, filenames and modification dates of the photos before an import. Specifically optimized for my devices used, because each has its peculiarities unfortunately. At the beginning I had to test which information is responsible for sorting the files. But in the meantime I have it under control.

Ok. Thank you for the insights.

Changing the main source file is a bit against the assumtions for design decisions of the gallery, but it will do, too.

In that case the purging of orphan files makes more sence since now and than the preview files (images and videos) have to be processed again under a different content based key (by SHA1) and will produce deprecated files.

Few days ago I published 1.8.2 with the support of purging orphan files. See the new [storage purge command](https://docs.home-gallery.org/cli/index.html#storage-command). E.g.

```
./gallery.js storage -s ~/.cache/home-gallery/storage purge -d ~/.config/home-gallery/database.db
```

Please do not hesitate to provide any feedback.

For curiosity: are you changing the video source files frequently, too?

> Overall, I would say that there are more important features than freeing the memory. E.g. a customizable size of the thumbs

I could not follow. Could you describe thes thumbs  feature request more in detail?

> or folders support instead of structuring via tags only.  I sort my files into folders and with each import, I try to set tags that map the folder structure. This way I can directly select and view a "folder". It's not that elegant but it seams to work for me.

In the detail view you can list all the files of a folder (including sub folders) by clicking a folder part. Would that help a bit?

What is your usecase to list the files by a specific folder? ... my assumtion is if I am interssted in a specific folder I will navigate that with a file browser/file explorer to work with originals or do postprocessing.

> Donwloading original files

Yes, I am slowly interessted in this feature, too :-)

> and configuration of preview resolutions via yaml would be very nice too...

Could you explain that use case, too?

**Comment by xemle** [comment]
> Oh and one simple thing drives me nuts :-) The font that symbolizes the current thumbnail as a video is gray. Most of the time I can't even read it, it's so small and gray. I'd love to set it to bold and white because there are barely any photos with pure white.

Thank you for your honest feedback. You are right.

Do you have suggestions/screenshots how to improve it (besides bold and white)? PRs are welcome, too

**Comment by onyxogen** [comment]
>   with each import, I try to set tags that map the folder structure. This way I can directly select and view a "folder". It's not that elegant but it seams to work for me.

I'll answer soon but right now I noticed that tagging was not possible anymore with version 1.8.2 ! Can you reproduce it?

**Comment by xemle** [comment]
> but right now I noticed that tagging was not possible anymore with version 1.8.2 ! Can you reproduce it?

Oh. Yes. Thank you for the hint. I will release soon a bug fix release. Thank you!

**Comment by xemle** [comment]
@onyxogen I published v1.8.3 with the fix for tagging. Enjoy

**Comment by onyxogen** [comment]
> For curiosity: are you changing the video source files frequently, too?

I haven't changed any video files yet, because my cameras always write the tags correctly - unlike the photos.

> > Overall, I would say that there are more important features than freeing the memory. E.g. a customizable size of the thumbs
> 
> I could not follow. Could you describe thes thumbs feature request more in detail?

Here's what I meant to describe: On my smartphone the thumbnails are displayed quite small. About 5 images on average per line. It would be helpful to be able to limit this to a maximum of 3 or 4 to be able to recognize the images better. The layouting in the desktop browser on the other hand is very good.

> > or folders support instead of structuring via tags only.  I sort my files into folders and with each import, I try to set tags that map the folder structure. This way I can directly select and view a "folder". It's not that elegant but it seams to work for me.
> 
> In the detail view you can list all the files of a folder (including sub folders) by clicking a folder part. Would that help a bit?

I know that, that's how I actually find my photos directly after an import. It is the only way directly after the import. However, I want a list where I can choose the appropriate folder directly. It is my entry point to my photo collection. Even though the endless stream of the start page is great, sometimes I want to access the pictures of a specific vacation, for example. And what's more, I want to get an textual impression of what "topics" I have. Then I go via the tags, where a list awaits me such as:

2021 - Costa Rica
2020 - Netherlands
2019 - Photos at home 

and so on.

This way I can quickly get to the topics.

> What is your usecase to list the files by a specific folder? ... my assumtion is if I am interssted in a specific folder I will navigate that with a file browser/file explorer to work with originals or do postprocessing.

I can't navigate the folder while I am on mobile connection very good. Even if I publish my folder on an smb connection, it is really slow and laggy. So for the use case at home it would be ok, but not on the road. Plus I'm sharing my libraries with some people who only can use a browser but nothing more... ;-)

> > and configuration of preview resolutions via yaml would be very nice too...
> 
> Could you explain that use case, too?

Images are compressed in 5 specific resolutions, videos are also compressed according to specific settings. 
However, I have high-resolution devices where I would like to have more resolution to see details better (after calling up the image, so not in the overview), even if it means that a photo needs a little more storage space.
Compared to Google Photos, the images are a bit too poorly resolved for me, or the compression settings are set too conservatively. Therefore you could provide a setting to manipulate the 5 resolution settings.

I'd like to do PRs but I couldn't find my way through javascript programming until now. 
But I must say, I really love home gallery, it's the only piece of software that comes close to my requirements and I'm on my way to drop Google photos slowly.

**Comment by onyxogen** [comment]
> > Oh and one simple thing drives me nuts :-) The font that symbolizes the current thumbnail as a video is gray. Most of the time I can't even read it, it's so small and gray. I'd love to set it to bold and white because there are barely any photos with pure white.
> 
> Thank you for your honest feedback. You are right.
> 
> Do you have suggestions/screenshots how to improve it (besides bold and white)? PRs are welcome, too

I'm sorry, bold and white has been the only suggestion I came up with :)

**Comment by onyxogen** [comment]
> @onyxogen I published v1.8.3 with the fix for tagging. Enjoy

Thanks for the fix - it works!

**Comment by xemle** [comment]
One more thing regarding embedded tagging: I understood that you are tagging your images and these tags are embedded into the main image file. Right?

If so the manual tagging of HomeGallery and the embedding tagging has some constrains/incompatibilities/drawbacks:

It is fine to embed the tags in the main file, import these files to HomeGallery and only manual tag them in the gallery afterwards. That is fine.

It will break if new tags gets embedded into the main file and the HomeGallery is updated. Than the manual tags loose their reference since the id changes.

Background: HomeGallery uses a content based id for its file references. So renaming and moving files around in the folder structure wont break the id. However changing a file by it contents, eg. embed tags leads to a new id. The manual tags in HomeGallery are using the id to reference the action.

Further a main file is defined as largest file in a file group built by their base name.

- IMG_1234.JPG
- IMG_1234.JPG.xmp
- IMG_1234.xmp

form a group file "IMG_1234" with `IMG_1234.JPG` as main file (or the biggest file) with its sidecar files `IMG_1234.JPG.xmp` and `IMG_1234.xmp`.

So HomeGallery assigns tags to `IMG_1234.JPG` from `IMG_1234.JPG` and its sidecar files `IMG_1234.JPG.xmp` and `IMG_1234.xmp.

The reason of this design decision was that the content of the main file is most crucial. Changing it needs high trust in the tools not breaking the file structure. And there were and there will be bugs in the tools. Create and changing sidecar files is not so crucial. If they break there is still the main file with its important media data. So the design decision is the main file should be handled as read only while side cars can be writeable.

So it is recommended in HomeGallery to embedded all important meta data (e.g. date fixes, author, copyrights, geo) before importing them to HomeGallery - or before using the manual tagging in HomeGallery.

**Comment by onyxogen** [comment]
Oh, I think there is a misunderstanding.
I should have always written "EXIF-Tag" and "Tag". The first one I use for sorting the photos because HomeGallery uses this. Note that a file explorer can sort based on different EXIF-Tags, File Date or name but Home Gallery don't, so I have to manipulate the tags to get a specific order in the web view.
I used this explanation only to state why I got certain invalid file imports that I needed to purge.

Then there is the Tag within HomeGallery you can modify via the UI which is total different kind of story, and everything else I reported concerns that exclusively.

**Comment by xemle** [comment]
> Note that a file explorer can sort based on different EXIF-Tags, File Date or name but Home Gallery don't, so I have to manipulate the tags to get a specific order in the web view.

I can not follow completely. How do you manipulate which tags to get a specific order in the web view? With tags you mean your general folder structure?

Regarding the folder structure and feature request please feel free to open a separate issue.

If the original request with purging is solve, please close this ticket.

**Comment by onyxogen** [comment]
> > Note that a file explorer can sort based on different EXIF-Tags, File Date or name but Home Gallery don't, so I have to manipulate the tags to get a specific order in the web view.
> 
> I can not follow completely. How do you manipulate which tags to get a specific order in the web view? With tags you mean your general folder structure?

No, I manipulate EXIF-Tags, basically all with the string "Date" in it: I use a python script that writes all Date-ExifTags to the same Date. Tags in Home-Gallery have nothing to do with it, because they are an proprietary feature. I don't know how to better explain it.
But it's not problematic, I can help myself and I have to, because the problem only exists because I use multiple types of cameras at thet same time. It's not a typical case, because normally someone picks its phone and uses the phone camera app and that's it.

**Comment by xemle** [comment]
> Tags in Home-Gallery have nothing to do with it, because they are an proprietary feature.

Well, yes. It is at the moment a proprietary feature. The idea is to export these tags into xmp sidecar files via the export command. But currently this feature is not requested yet and I do not require it yet either. But do not hesitate to request it ;-)

> I don't know how to better explain it.

Yes. What a pity. Unfortunately I still don't get it. I am very sorry for that.
