### ISSUE TITLE
Can I set password access?

### ISSUE THREAD

**Issue by flytkgl** [xemle/home-gallery#56]
Can I set password access?

and

Can you provide the armv8 binary file

**Comment by xemle** [comment]
Hi @flytkgl 

Thank you for reaching out.

Unfortunately I can not follow your questions and I am trying to answer as best as I can

> Can I set password access?

It is possible to set basic auth for the server. See the [example config](https://github.com/xemle/home-gallery/blob/master/gallery.config-example.yml#L122) and its comments

> Can you provide the armv8 binary file

Currently armv8 is not supported. You should be able to use docker on armv8 or the [home-gallery-latest-all-generic.tar.gz](https://dl.home-gallery.org/dist/latest/home-gallery-latest-all-generic.tar.gz) without node environment, ffmpeg, ffprobe and sharp. These needs to be installed by the user. See [the docs](https://docs.home-gallery.org/install/index.html#generic-application-bundle) for help.

If you have further questions, please do not hesitate to comment here.

**Comment by xemle** [comment]
Hi @flytkgl 

Thank you for reaching out.

If you are using generic tarball you need to set the external commands convert/vipsthumbnail, perl, ffmpeg and ffprobe so that the previews can be rendered. See [install generic-application-bundle](https://docs.home-gallery.org/install/index.html#generic-application-bundle). The generic bundle does not come with these tools and needs to be configured manually. Basically these tools needs to be in the `PATH` and you tell the gallery to use them.

Further, your screenshot looks like the preview calculation did not work. Please run a full import `./gallery.js run import` without `--initial` or `--update` argument to fix that.

If that does not help, please inspect or send your `gallery.log` from `/data/adb/modules/home-gallery/.config/home-gallery`. [jq](https://stedolan.github.io/jq/) will be your friend to inspect the log.

**Comment by flytkgl** [comment]
I have added `node/convert/ffmpeg/ffprobe` to `PATH`,No `perl`, `./gallery.js run import` and `./gallery.js run import --initial` and `./gallery.js run import --update`  I've tried them all

[gallery.log](https://github.com/xemle/home-gallery/files/10010726/gallery.log)

**Comment by xemle** [comment]
Hi @flytkgl 

Thank you for providing the log. I was hoping to identify a problem here but could not find any.

HomeGallery uses also exiftool to extract meta data from images. So the generic bundle requires also perl binary to be in the `PATH`. I have checked how HomeGallery behaves if perl is not available and it seems that it fails silently and no file is stored in the storage directory. Is it possible to install perl on your side, too? 

Then you can check the storage directory. Within the storage directory `/data/adb/modules/home-gallery/.cache/home-gallery/storage` there should be some files of exiftool with `-exif.json` suffix and image previews such as `-image-preview-1280.jpg` suffix like outlined in the [internal docs](https://docs.home-gallery.org/internals/index.html#storage-directory). Could you list the files of some directories here?

**Comment by flytkgl** [comment]
After I installed `perl` to `PATH`, it is now normal
It feels like you have too many external dependencies. I would prefer to make it a static binary file
Like https://github.com/navidrome/navidrome

**Comment by xemle** [comment]
> After I installed `perl` to `PATH`, it is now normal

Awesome! Thank you for the update

> It feels like you have too many external dependencies. I would prefer to make it a static binary file
> Like https://github.com/navidrome/navidrome

Thank you for the input. PRs are welcome to build the static binary.

HomeGallery uses [caxa](https://github.com/leafac/caxa) to bundle the binary. caxa 2.0.0 supports armv8, too. So basically HomeGallery could also provide binary bundles for armv8 besides its given OSs Linux/arm64, Mac and Windows.

**Comment by xemle** [comment]
> Can I set password access?

@flytkgl is your initial request solved?

**Comment by flytkgl** [comment]
> > Can I set password access?
> 
> @flytkgl is your initial request solved?

YES,it is OK
