### ISSUE TITLE
Bug: Playing a video on google chrome browser on android does not work

### ISSUE THREAD

**Issue by onyxogen** [xemle/home-gallery#64]
Clicking on the play button does not play the video. 
Clicking outside of it (upper or lower part) works.

**Comment by xemle** [comment]
The problem is, that HomeGallery uses browser's default video player which uses ShadowDOM to build the UI, containing a central play icon. To support the swiping to next/prev an overlay element above the video element is required. Somehow the central play is not covered by the overlay and it starts and immediately stops the video. The video is playable by tapping around the central play icon.

I was not able to get the overlay above the central play icon to fix the problem. The central play icon can be hidden on webkit browsers (like Chrome) to fix the visual quirks. Would that be fine?

**Comment by onyxogen** [comment]
I think it's valuable to have an information that you need to click in order to play. Maybe you could hide the central play button and replace it by a custom image (the play button) or text?
Removing it completely would be the last resort I think :)

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
