### ISSUE TITLE
Potential Bug? - Spawning a huge number of containers? 

### ISSUE THREAD

**Issue by tokenwizard** [xemle/home-gallery#67]
@xemle  I messages you on Matrix about this, but I'm not sure how frequently that gets checked. 

The only docker service I'm running on this device is home-gallery (running via docker-compose). I did a 
`docker-compose down`
so I could rename the folder I'm running it from and noticed that there was a large number of containers it was removing. I stopped that after about 15 minutes because it was still not done and seemed to be frozen. 

Then I listed the docker containers directory on the server:
![image](https://user-images.githubusercontent.com/24832561/212345796-dadd0430-a6e7-4eed-8364-7b0b60f99a91.png)

Is it expected for home-gallery via docker-compose to generate so many containers? 

![image](https://user-images.githubusercontent.com/24832561/212345991-7f4a82a4-199d-4829-97ee-0e707152b098.png)

**Comment by xemle** [comment]
Hi @tokenwizard 

No that is not the expected behavior. I've checked mine setup on my RPi with `docker ps`. For homegallery there should be only 2 containers running: One server and one api container.

Currently I have no clue why you have spawned containers. Are you using the docker compose from the [docs.home-gallery.org](https://docs.home-gallery.org/install/index.html#docker-compose)?

**Comment by tokenwizard** [comment]
Yes, that is the docker-compose file I am using. I did have to change the version string to just "3" because for some reason it didn't like that one that was there. 

![image](https://user-images.githubusercontent.com/24832561/212404283-dfaa4e01-74e6-4570-95f3-08d648ec68a7.png)


I stopped the docker services, rebooted the server, manually removed all the docker container folders from /var/lib/docker/containers/ and then restarted the home-gallery via docker-compose up -d. 

After a couple hours, this is what I have:
![image](https://user-images.githubusercontent.com/24832561/212404479-efa1ab00-c4ee-4ec0-bba4-5a5d494c12bb.png)

It's the strangest thing. I have another server that I am running multiple docker containers on and don't ever see this behavior.

**Comment by tokenwizard** [comment]
FYI, this is running in a ProxMox LXC but that has not been an issue for any of my other Docker deployments.

**Comment by xemle** [comment]
Have you investigated the logs of docker-compose? Maybe the container is not able to start and is restarted and restarted again? BTW I am in Gitter/Matrix

**Comment by tokenwizard** [comment]
Ok, the issue was caused by me running what I thought was the correct command to refresh/update the database within the docker container. Instead, the command was causing it to run new instances of the docker container. 

THE CORRECT way to script the update of the database to pull in new images that get uploaded to the source directory is below. 

![image](https://user-images.githubusercontent.com/24832561/212549528-36b62568-49e6-484d-8a3e-10cec33bcd28.png)

You can then run this script from a cron job on the host to run the update command inside the running docker container. This example runs the database refresh every 15 minutes.
`*/15 * * * * /path/to/galleryRefresh.sh
`

**Comment by galgofa** [comment]
I have the same issue, after each time i use update with "docker-compose run gallery run import --update" it is appearing new container with uniq name like "home-gallery_gallery_run_8b99...", it is appeared as stopped after scan in the list and stay there where new containers appears on each scan attempt...
The docker-compose is as per suggestion in the docs manuals.
Any help please.

**Comment by tokenwizard** [comment]
Add the -T flag, based on some conversation with the developer. I think that might be missing from the docs.

I had to 'docker-compose down' then reboot and manually remove all the containers from /var/lib/docker/containers.

Then I did a 'docker-compose up -d' to bring home-gallery back online.

Once running again, use 'docker-compose run -T gallery run import --update' to refresh the database and see if it spawns new containers again.

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by galgofa** [comment]
Unfo doesn't work, after -T same, appeared of another container "home-gallery_gallery_run_df77..."

**Comment by xemle** [comment]
Hi @galgofa thank you for reaching out and using Home Gallery.

`run import --update` is meant to check for new files, create all preview files, create mobile friendly videos and update the database. This process can take time especially on many new files, large videos or low powered systems.

To `run import --update` makes only sense if a) most of your files are all already imported b) the interval is longer than a single update run. Otherwise a single `run import` is recommended to build and bootstrap your media gallery.

If you have lots of videos and a low powered system choose a longer interval to finish all new video conversion on the update job. Otherwise the video conversion is started all over again in parallel, system resources are allocated and the system becomes slower and slower.

Have you checked the output of a single container? Maybe increase the log level to see more messages what is going on. Further `docker-compose run -T gallery run import --update` runs a new container while `docker-compose exec -T gallery run import --update` runs in an existing container. I recommend the later.

**Comment by tokenwizard** [comment]
> Hi @galgofa thank you for reaching out and using Home Gallery.
> 
> `run import --update` is meant to check for new files, create all preview files, create mobile friendly videos and update the database. This process can take time especially on many new files, large videos or low powered systems.
> 
> To `run import --update` makes only sense if a) most of your files are all already imported b) the interval is longer than a single update run. Otherwise a single `run import` is recommended to build and bootstrap your media gallery.
> 
> If you have lots of videos and a low powered system choose a longer interval to finish all new video conversion on the update job. Otherwise the video conversion is started all over again in parallel, system resources are allocated and the system becomes slower and slower.
> 
> Have you checked the output of a single container? Maybe increase the log level to see more messages what is going on. Further `docker-compose run -T gallery run import --update` runs a new container while `docker-compose exec -T gallery run import --update` runs in an existing container. I recommend the later.

@xemle It seems the Documentation should be updated. This is what it says there and may be why we are seeing this issue:

![image](https://user-images.githubusercontent.com/24832561/215525281-5ac8b5ba-a472-49ae-9491-6dbb69c1b979.png)

**Comment by xemle** [comment]
Thank you for the hint. Feel free to open a PR on https://github.com/xemle/home-gallery-doc/blame/master/source/install/docker-compose.rst#L38

Whether you use `docker-compose run` or `docker-compose exec`: I guess that the problem of spawning is caused by the long running import and the short interval of calling the action again and again.

Unfortunately I was not able to reproduce the issue on my local setup. Since I can only give a best guess from remote, please do not hesitate to provide feedback on the log output or details of your new files or video amounts to clarify this issue in detail.

**Comment by tokenwizard** [comment]
I ran the initial import and did not run the "refresh" ones until it had completed. For each subsequent "refresh" there were only a handful (less than 10) new photos to import, so I can't imagine it taking more than 5 minutes.

I implemented an alternate solution I documented above that is working well now, but I see you are working on adding a built-in refresh/watch option that should make all of these difficulties go away.

------- Original Message -------

**Comment by xemle** [comment]
> Thank you for the hint. Feel free to open a PR on https://github.com/xemle/home-gallery-doc/blame/master/source/install/docker-compose.rst#L38

@galgofa Mm. It is tricky regarding `exec` and `run`. With `exec` you need to give also the script to run:

```
docker-compose exec gallery /app/gallery.js run import
```

while with `run` you can just run


```
docker-compose run gallery run import
```

Sorry for the inconvenience. So I improve my previous answer to use `run` instead of `exec`. 

But maybe this discussion is just outdated. See last comments on #35 regarding the new `--watch` option on the import.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
