### ISSUE TITLE
Feature Request: Add timestamp for stdout/stderr

### ISSUE THREAD

**Issue by martadinata666** [xemle/home-gallery#82]
Maybe it's just me, but I think this is pretty neat to have. Or is this already supported? I can't find something like `log format`. 🤔 

Current:
```
extractor.image.resize Use sharp to resize images
index.readStream Reading file index journal /data/config/Pictures.idx.0619-t2lc.journal
cli.extract Extract all meta data and calculated all preview files from 0 entries
cli.spawn Run cli with database --index /data/config/Pictures.idx --journal 0619-t2lc --storage /data/storage --database /data/config/database.db
index.readStream Reading file index journal /data/config/Pictures.idx.0619-t2lc.journal
database.build Created 0 database entries
```

Expected
```
[dd/mm/yy time] extractor.image.resize Use sharp to resize images
index.readStream Reading file index journal /data/config/Pictures.idx.0619-t2lc.journal
[dd/mm/yy time] cli.extract Extract all meta data and calculated all preview files from 0 entries
[dd/mm/yy time] cli.spawn Run cli with database --index /data/config/Pictures.idx --journal 0619-t2lc --storage /data/storage --database /data/config/database.db
index.readStream Reading file index journal /data/config/Pictures.idx.0619-t2lc.journal
[dd/mm/yy time] database.build Created 0 database entries
[dd/mm/yy time] database.mergeJournal Read file index journal /data/config/Pictures.idx.0619-t2lc.journal
```

Thanks.

**Comment by xemle** [comment]
Hi @martadinata666 

Thank you for reaching out and using HomeGallery. Could you explain why you like to have a timestamp in the stdout logging? What problem/issue would it solve for you?

The requested formatting is not supported yet. The stdout logging output is done in [pretty-stream](https://github.com/xemle/home-gallery/blob/master/packages/logger/src/pretty-stream.js#L56) in the logger package. Feel free to provide the formatting feature and if you have further questions, please post them here.

Some background for the current state: The stdout does not contain timestamp because it was migrated from [debug](https://www.npmjs.com/package/debug) to the logging framework [pino](https://getpino.io/) and debug had not timestamp.

The log file are in ndjson format and containing the timestamp and additional information - provided by pino. These fields could be a base for the formatting.

**Comment by martadinata666** [comment]
Thanks, primarily I'm looking at the timestamp to see the batch addition/extraction of photos. Just in case some batches errored, but so far the software pretty reliable itself.

And talking about `pino` the frontend page show that it got timestamp but in epoch, thus also pino-pretty convert this to human readable.
Pino frontpage
```
{"level":30,"time":1531171074631,"msg":"hello world","pid":657,"hostname":"Davids-MBP-3.fritz.box"}
```
[Pino-pretty](https://github.com/pinojs/pino-pretty)
```
[17:35:28.992] INFO (42): hello world
```
And this line ignore `time`? https://github.com/xemle/home-gallery/blob/c3eeb57a089bee4bd1e81e4136acf67dc474ad88/packages/logger/src/pretty-stream.js#L50 ?

**Comment by xemle** [comment]
> Thanks, primarily I'm looking at the timestamp to see the batch addition/extraction of photos. Just in case some batches errored, but so far the software pretty reliable itself.

OK. In case of errors I inspect the log, since this contains a lower logging level and sometimes additional information than the stdout. I juse [jq](https://jqlang.github.io/jq/) to inspect the log messages.

So I mainly use the stdout as kind of progress bar/alive indicator

> And talking about `pino` the frontend page show that it got timestamp but in epoch, thus also pino-pretty convert this to human readable. Pino frontpage
> 
> ```
> {"level":30,"time":1531171074631,"msg":"hello world","pid":657,"hostname":"Davids-MBP-3.fritz.box"}
> ```
> 
> [Pino-pretty](https://github.com/pinojs/pino-pretty)
> 
> ```
> [17:35:28.992] INFO (42): hello world
> ```

As I wrote the debug package was original used and I migrated pino in the outmode of debug. That is the reason why the the logging of HomeGallery does not look like the example message of [pino-pretty](https://github.com/pinojs/pino-pretty).

I am fine if this got changed.

> And this line ignore `time`?
> 
> https://github.com/xemle/home-gallery/blob/c3eeb57a089bee4bd1e81e4136acf67dc474ad88/packages/logger/src/pretty-stream.js#L50
> ?
> 
> Trying to rebuild myself, by enabling `time` and `hostname`, got this log
> 
> ```
> [08:09:15.323] (on instasave): database.build Created 0 database entries
> [08:09:15.328] (on instasave): database.mergeJournal Read file index journal /data/config/Pictures.idx.0620-FZFL.journal
> [08:09:15.328] (on instasave): cli.database Database unchanged: Error: Journals contain no changes
> [08:09:15.336] (on instasave): cli.spawn Run cli with index journal --index /data/config/Pictures.idx --journal 0620-FZFL -r
> [08:09:15.580] (on instasave): index.journal Remove journal 0620-FZFL from file index /data/config/Pictures.idx
> ```
> 
> Personally it feels sleek and clean, prettified. 🤞🏼

You can raise a PR to change that.

FYI HomeGallery overwrites pinos default EPOCH timestamp to [ISO timestamp here](https://github.com/xemle/home-gallery/blob/c3eeb57a089bee4bd1e81e4136acf67dc474ad88/packages/logger/src/index.js#L27)

> Other than time, I see the hostname, is the api/tensorflow usable by multiple gallery instances?

Yes, the api server can be used by multiple instances like the default and public api https://api.home-gallery.org

Background here is: That I had an CPU which was not supported by tensorflow so I had to externalized this by an server. This had also the advantage to support low powered machines like Rasperry PI Zero.

Now tensorflow supports the wasm backend which can be run everywhere where nodejs runs.

> and is also using the same logging method? if it does then enabling hostname maybe worth looking for.

The api server did not get much attention and the logging is not by [morgan](https://www.npmjs.com/package/morgan). It would be nice to have here pino as well. Feel free to add it there
