### ISSUE TITLE
Feature: Filter by multiple tags, and create view from it

### ISSUE THREAD

**Issue by gaelL** [xemle/home-gallery#89]
Currently, you can filter by only one tag, it would be really great to be able to filter by selecting several tags.

For example with this sample of pictures-tags:

```
pic1 - tags: bus
pic2 - tags: car, red
pic3 - tags: car, blue
pic4 - tags: boat, green
```

Be able to look only for `red, car` tags.

In addition to this, be able to save those filters ideally as "view" (kind of albums).

This will provide for user a way to group and create dynamic views/albums based on tags. For example an album containing only red cars.

**Comment by xemle** [comment]
Hi @gaelL thank you for using HomeGallery and for reaching out.

> Currently, you can filter by only one tag, it would be really great to be able to filter by selecting several tags.

The search is able to search for several tags. By default all given tags are searched as AND boolean expression. So "tag:red tag:blue" is the same as "tag:red and tag:blue" and will list all images having both tag sred and blue.

If you looking for an OR boolean expression pleas use "tag:red or tag:blue"

Futher details can be found at [search docs](https://docs.home-gallery.org/webapp/index.html#search)

**Comment by xemle** [comment]
> In addition to this, be able to save those filters ideally as "view" (kind of albums).

That is an great idea. Since this gallery is a spare time open source project I am happy to support creating an PR for it. Otherwise this feature request gets on the pile of great ideas until time comes to solve each.

I am happy for everyone unsing HomeGallery. But I do also understand if other alternatives fits more to someone in terms of features or development speed. PhotoPrism, Immich or LibrePhotos are some example to test.

**Comment by xemle** [comment]
Closing it due inactivity. Please do not hesitate to reopen it if required.
